# Generated by Django 4.2.1 on 2023-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='desc',
            field=models.TextField(),
        ),
    ]
