# Generated by Django 4.2.1 on 2023-05-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0004_alter_feedback_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedback1',
        ),
    ]
