# Generated by Django 4.2.1 on 2023-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0005_rename_feedback_feedback1'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=54)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
