# Generated by Django 4.2.1 on 2023-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksapp', '0006_mailm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailm',
            name='addr',
            field=models.TextField(default=30),
            preserve_default=False,
        ),
    ]
